name: vsc_pdf_template_editor
description: Interactively edits PDF templates.
version: 0.0.1
homepage: https://github.com/VisualSystemsCorp/vsc_pdf_template_editor
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5
  pdf: ^3.8.3
  printing: ^5.9.2
  vsc_pdf_template_transformer:
    path: ../vsc_pdf_template_transformer
  easy_debounce: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true
