name: vsc_pdf_template_editor
description: Interactively edits PDF templates.
version: 0.0.1
homepage: https://github.com/VisualSystemsCorp/vsc_pdf_template_editor
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5
  pdf: ^3.10.8
  printing: ^5.12.0
  vsc_pdf_template_transformer:
    git:
      url: https://github.com/VisualSystemsCorp/vsc_pdf_template_editor.git
      path: vsc_pdf_template_transformer
  file_picker: ^8.0.6
  flutter_code_editor: ^0.2.18
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  queue: ^3.1.0+2

dependency_overrides:
  # For local development working on the transformer and the editor.
  vsc_pdf_template_transformer:
    path: ../vsc_pdf_template_transformer

  http: ^1.1.0

  # file_picker issue:
  win32: 5.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true
