name: vsc_pdf_template_editor
description: Interactively edits PDF templates.
version: 0.0.1
homepage: https://github.com/VisualSystemsCorp/vsc_pdf_template_editor
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5
  pdf: ^3.8.3
  printing: ^5.9.2
  vsc_pdf_template_transformer:
    # For local development working on the transformer and the editor, you may need to uncomment this, but don't check it in.
    #path: ../vsc_pdf_template_transformer
    git:
      url: https://github.com/VisualSystemsCorp/vsc_pdf_template_editor.git
      path: vsc_pdf_template_transformer
  easy_debounce: ^2.0.2+1
  file_picker: ^5.2.4
  flutter_code_editor: ^0.2.4
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true
