name: vsc_pdf_template_transformer
description: Transforms templates created by vsc_pdf_template_editor into finished PDF documents.
version: 0.0.1
homepage: https://github.com/VisualSystemsCorp/vsc_pdf_template_editor
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  expressions: ^0.2.4
  path: ^1.8.2
  pdf: ^3.8.3
  printing: ^5.9.2
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  test: ^1.21.5
  json_serializable: ^6.3.0
