name: vsc_pdf_template_transformer
description: Transforms templates created by vsc_pdf_template_editor into finished PDF documents.
version: 0.0.1
homepage: https://github.com/VisualSystemsCorp/vsc_pdf_template_editor
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  expressions: ^0.2.5
  path: ^1.8.2
  pdf: ^3.11.1
  json_annotation: ^4.7.0
  timezone: ^0.9.0
  intl: ^0.18.0
  decimal: ^2.3.2
  rational: ^2.2.2
  http: ^1.1.0
  meta: ">=1.3.0 <2.0.0"
  vector_math: ^2.1.0
  xml: ">=5.1.0 <7.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  test: ^1.21.5
  json_serializable: ^6.3.0
