class AppConstants {
  static List<String> supportedWidgets = [
    'Text',
    'Sized Box',
    'Container',
    'Column',
    'Row',
    'Repeater',
    'Header',
    'New Page',
    'Spacer',
    'Expanded',
    'Center',
    'Divider',
    'Full Page',
    'Padding',
    'Placeholder',
    'Align',
    'Aspect Ratio',
    'Checkbox',
    'Constrained Box',
    'Decorated Box',
    'Fitted Box',
    'Flex',
    'Flexible',
    'Flat Button',
    'Footer',
    'Grid View',
    'Limited Box',
    'Image',
    'Svg Image',
    'Stack',
    'Positioned',
    'List View',
    'Link',
    'Url Link',
    'Paragraph',
    'Vertical Divider',
    'Watermark',
    'Wrap',
    'Table'
  ];
  static List<String> supportedProperties = [
    'Alignment',
    'Edge Insets',
    'Box Decoration',
    'Radius',
    'Box Border',
    'Box Constraints',
    'Border Style',
    'Border Radius',
    'Border Side',
    'Text Style',
    'Page Format',
    'Decoration Image',
    'Decoration Svg Image',
    'Table Border',
    'Table Row',
    'Intrinsic Column Width',
    'Fixed Column Width',
    'Flex Column Width',
    'Fraction Column Width',
    'Linear Gradient',
    'Radial Gradient',
    'Fractional Offset'
  ];

  static List<String> supportedImages = [
    'Memory Image',
    'Raw Image',
  ];
}
